= Groovy StreamSum - summing Numbers with streams

== The F# Challenge

My friend @hexsprite is learning *F#* and sent me his first F# program:

[source]
----
let square x = x * x
let sumOfSquares n = [1..n] |> List.map square |> List.sum
sumOfSquares 100 |> printfn "result: %i"
----

I told him I'd write it in *Groovy* and *Java* using Streams and send it to him. I figured it was
a good opportunity to learn how to use Java Streams in Groovy -- which I hadn't done before. I
found that it wasn't as Groovy as I expected, so I decided to write some extension functions to make it
_Groovy_ again.

== Implementation the Challenge in Java and Groovy


=== Java Decisions

To write this in Java there was a choice to be made:

* Which type of number, `Integer` or `int`, etc.?

Since `IntStream` provides _range_ functions and `.sum()`, using `int` was the easy choice.

=== Groovy Decisions

In Groovy there were at least four choices to be made:

* Use Java Streams or Groovy Collections?
* Which type of number, `Integer` or `int`, etc.?
* Use lambdas or closures?
* `var`, `def`, or explicit type?

Since Groovy collections aren't equivalent to streams in *F#*, the answer to the first question is to use Java Streams. Since Java Streams can only sum primitive types, I chose `int` (and therefore `IntStream`) for the number type. Since I wanted the Java and Groovy examples to be as similar and directly-comparable as possible, I used `var` for defining variables and lambdas rather than Groovy Closures. The `var` keyword and Java lambda syntax are both new in Groovy 3.

=== The Java Implementation

.SumOfSquares.Java
[source,java]
----
import java.util.function.IntUnaryOperator;
import static java.util.stream.IntStream.rangeClosed;
import static java.lang.System.out;

public class SumOfSquares {
    public static void main(String[] args) {
        IntUnaryOperator square = x -> x * x;
        IntUnaryOperator sumOfSquares = n -> rangeClosed(0,n).map(square).sum();
        out.println("result: " + sumOfSquares.applyAsInt(100));
    }
}
----

By using `import static` twice, I was able to _cheat a little_ and send him just these three lines:

.Java "cheat a little" excerpt
[source,java]
----
IntUnaryOperator square = x -> x * x;
IntUnaryOperator sumOfSquares = n -> rangeClosed(0,n).map(square).sum();
out.println("result: " + sumOfSquares.applyAsInt(100));
----

NOTE:: Using `var` for the declaration of the lambdas doesn't work in Java.


=== The Groovy Implementation

The first example `SumOfSquaresIdiomatic.groovy` shows the nice, easy-to-read, idiomatic Groovy code that we
would expect. Unfortunately, it is not using Java `Stream`, so it is not possible to add more Stream operations
to the pipleine and isn't really an equivalent implementation of the original *F#* code.

.SumOfSquaresIdiomatic.groovy
[source,groovy]
----
var square = x -> x * x
var sumOfSquares = n -> (0..n).collect(square).sum()
println "result: ${sumOfSquares(100)}"
----

The second groovy example `SumOfSquares.groovy` is probably the best we can do with current Groovy without the use of any extensions. Java `Object` Streams do not have a `.sum()` operation, but Java Streams that use primitive numberic types do have `.sum()`. So we use the `.mapToInt()` function to convert from `Stream` to `IntStream` so we can use `.sum()`. This is the code I sent to @hexsprite.

.SumOfSquares.groovy
[source,groovy]
----
var square = x -> x * x
var sumOfSquares = n -> (0..n).stream().mapToInt(x -> x).map(square).sum()
println "result: ${sumOfSquares(100)}"
----

This repository contains a prototype implementation of a few Groovy extensions, including a `.sum()` method for `Stream` that will work on `Object` streams containing `Number` subclasses (throwing a `ClassCastException` otherwise.) This results in a nice, idiomatic Groovy implementation of the original *F#* code.  (Well, except for the stream operator `|>` and the ability to stream to `println` which is a subject for another day.)

This is the code I wanted to send to @hexsprite, but couldn't -- until after I wrote the Extension.

.SumOfSquaresUsingExtension.groovy
[source,groovy]
----
var square = x -> x * x
var sumOfSquares = n -> (0..n).stream().map(square).sum()
println "result: ${sumOfSquares(100)}"
----

== The Extensions

To enable the extensions in your project simply include `groovy-stream-sum-0.1.jar` in your project's runtime classpath.

=== StreamSum

Using link:src/main/groovy/com/msgilligan/groovy/streamsum/StreamSum.groovy[StreamSum] can now use `.sum()` on `Object` streams, like this:

[source,groovy]
----
assert (0..100).stream().sum() == 5050
----

NOTE:: If the `Stream` contains non-numeric types (or types that don't have any `.asType()` conversions to numbers) you'll get a `ClassCastException`.

For more examples see the Spock test: link:src/test/groovy/com/msgilligan/groovy/streamsum/StreamSumSpec.groovy[StreamSumSpec.groovy]

=== CollectionPrimitiveSteam

link:src/main/groovy/com/msgilligan/groovy/streamsum/CollectionPrimitiveStream.groovy[CollectionPrimitiveSteam] adds three methods to any `Collection` allowing you to get create the three Java primitive stream types: `IntStream`, `LongStream`, `DoubleStream`, like this:

[source,groovy]
----
assert [0i, 1i].intStream().sum() == 1
assert [0L, 1L].longStream().sum() == 1L
assert [0.0, 1.0].doubleStream().sum() == 1.0d
----

NOTE:: If the `Collection` contains non-numeric types (or types that don't have any `.asType()` conversions to numbers) you'll get a `ClassCastException`.

For more examples see the Spock test: link:src/test/groovy/com/msgilligan/groovy/streamsum/CollectionPrimitiveStreamSpec.groovy[CollectionPrimitiveStreamSpec.groovy]


